### ISSUE TITLE
hfs mounted macintosh hd on device root_device

### ISSUE THREAD

**Issue by granda** [AndrewDryga/vagrant-box-osx-mavericks#2]
When attempting to boot with `vagrant up` it stalls on attempting to connect over `ssh`. I flipped the switch in the Vagrant file for the GUI and the issue seems to be that it stalls on booting with:

`hfs mounted macintosh hd on device root_device`

**Comment by granda** [comment]
Working for me as well, thanks.

**Comment by gfody** [comment]
thank you!
